[workspace]
members = ["crates/*"]
resolver = "3"

[package]
name = "ziege"
version = "0.1.0"
edition = "2024"

[dependencies]
dotenvy = "0.15"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
zadt = { version = "0.1.0", path = "./crates/zadt/", features = ["logging"] }
zvfs = { version = "0.1.0", path = "./crates/zvfs/" }
